export const FLOW = {
    NOFLOW: "NOFLOW",
    STARTUP: "STARTUP",
    FIRSTGAME: "FIRSTGAME",
    LEVELSELECT: "LEVELSELECT",
    HIGHSCORESELECT:"HIGHSCORESELECT",
    SURVEY:"SURVEY",
    HIGHSCORE: "HIGHSCORE",
    ABOUT:"ABOUT"

}