export const SCENES = {
    LOAD: "LOAD",
    PLAY: "PLAY",
    TRACKING: "TRACKING",
    HUD: "HUD",
    GAMEOVER: "GAMEOVER",
    MENUBACKGROUND: "MENUBACKGROUND",
    MAINMENU: "MAINMENU",
    INFOMENU: "INFOMENU",
    LEVELSELECT: "LEVELSELECT",
    HIGHSCORE: "HIGHSCORE",
    ABOUT: "ABOUT"
}
